export const environment = {
  production: true,
  hatariumApiBaseUrl: 'http://localhost:3000',
  hatariumRolesEndpointPath: '/roles',
  hatariumAccountsEndpointPath: '/accounts',
  hatariumUsersEndpointPath: '/users',
  hatariumAnimalsEndpointPath: '/animals',
  hatariumLotsEndpointPath: '/lots',
  hatariumMovementsEndpointPath: '/movements',
  hatariumFeedingPlansEndpointPath: '/feedingPlans',
  hatariumFeedingPlanItemsEndpointPath: '/feedingPlanItems',
  hatariumFeedingLogsEndpointPath: '/feedingLogs',
  hatariumAppointmentsEndpointPath: '/appointments',
  hatariumAppointmentAnimalsEndpointPath: '/appointmentAnimals',
  hatariumMedicalRecordsEndpointPath: '/medicalRecords',
  hatariumMedicationsEndpointPath: '/medications',
  hatariumTreatmentsEndpointPath: '/treatments',
  hatariumVaccinesEndpointPath: '/vaccines',
  hatariumPregnanciesEndpointPath: '/pregnancies',
  hatariumPaymentsEndpointPath: '/payments',
  hatariumTransactionsEndpointPath: '/transactions',
  hatariumReceiptsEndpointPath: '/receipts',
  hatariumReportsEndpointPath: '/reports',
  hatariumReportSharesEndpointPath: '/reportShares',
  hatariumNotificationsEndpointPath: '/notifications'
};
